### ISSUE TITLE
Pinch zoom

### ISSUE THREAD

**Issue by silaslira** [viktorhajer/simple-pdf-viewer#12]
Is it possible to zoom using pinch gesture instead of buttons?

Thank you!

**Comment by viktorhajer** [comment]
The library just provides the API for the zoom functionality so it depends on the framework how to use it. So you have to implement this feature in your own app. E.g. I created a touch directive in one of my applications to have that user friendly control on the touch devicses (it won't be public because I don't have enough time to clean-up).
