### ISSUE TITLE
missing print button

### ISSUE THREAD

**Issue by kaniobjmed** [viktorhajer/simple-pdf-viewer#32]
hey guys, i would like to print the pdf document like what adobe pdf reader does have the default printer,
Is that any way to add action bar in that viewer?

**Comment by viktorhajer** [comment]
I'm not planning to implement the print functionality for the API because it would be hard to do it in device independent way. So it wont be part of the demo page as well... 
But you can fork this repo, and create your own viewer with the print button. Maybe you only need to call the window.print(); method.
